//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApplicaceRentalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItem
    {
        public int Id { get; set; }
        public string ItemTypeName { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Dimensions { get; set; }
        public string Colour { get; set; }
        public string EnergyConsumption { get; set; }
        public string MonthlyFee { get; set; }
    }
}
